name: windowsci

on: [push]

jobs:
  buildvsx86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: main
      working-directory: gep/Project/win32/
      run: |
           dir
           msbuild gepwin32.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: main
      working-directory: SNESticle/Project/win32/
      run: |
           dir
           msbuild win32.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
    - name: upload
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            "SNESticle/release/SNESticle - Win32.exe"
