name: windowsci

on: [push]

jobs:
  buildvsx86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: MSBuild x86
      working-directory: Project/win32
      run: |
           msbuild win32.vcxproj /m /property:Configuration=Release /property:Platform=x86 /verbosity:minimal
